<?php
declare(strict_types=1);
/**
 * This file is part of the Obsidian - ModernFrontend project.
 *
 * @license MIT License - See the LICENSE file in the root directory for details.
 * © 2024 Jeanmarcos Juarez
 */

namespace MageObsidian\ModernFrontend\ViewModel;

use InvalidArgumentException;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Locale\ResolverInterface as LocaleResolver;
use Magento\Framework\View\Asset\Repository;
use Magento\Framework\View\Element\Block\ArgumentInterface;
use MageObsidian\ModernFrontend\Api\Data\ConfigInterface;
use MageObsidian\ModernFrontend\Model\Config\ConfigProvider;
use MageObsidian\ModernFrontend\Service\EagerIslandRegistry;
use MageObsidian\ModernFrontend\Service\IslandManifest;
use MageObsidian\ModernFrontend\Service\Vue\PropsEncoder;
use RuntimeException;

class ViteResolver implements ArgumentInterface
{
    /**
     * Page-level island bootstrap, shipped as a module web asset. Discovers and
     * mounts the markers emitted by {@see self::renderVueComponent()}.
     */
    private const ISLANDS_RUNTIME_NAME = 'MageObsidian_ModernFrontend::js/islands';

    /**
     * Magento's native per-locale JS dictionary, materialized at
     * pub/static/<area>/<theme>/<locale>/js-translation.json during deploy.
     */
    private const JS_TRANSLATION_FILE = 'js-translation.json';

    /**
     * ViteResolver constructor.
     *
     * @param Repository $assetRepository
     * @param RequestInterface $request
     * @param ConfigProvider $configProvider
     * @param LocaleResolver $localeResolver
     * @param EagerIslandRegistry $eagerIslandRegistry
     * @param IslandManifest $islandManifest
     */
    public function __construct(
        private readonly Repository $assetRepository,
        private readonly RequestInterface $request,
        private readonly ConfigProvider $configProvider,
        private readonly LocaleResolver $localeResolver,
        private readonly EagerIslandRegistry $eagerIslandRegistry,
        private readonly IslandManifest $islandManifest
    ) {
    }

    /**
     * Retrieve url of a view file
     *
     * @param string $fileId
     * @param array $params
     *
     * @return string
     */
    public function getViewFileUrl(string $fileId, array $params = []): string
    {
        $params = array_merge(['_secure' => $this->request->isSecure()], $params);
        return $this->assetRepository->getUrlWithParams($fileId, $params);
    }

    /**
     * Get the full URL for a file generated by Vite.
     *
     * @param string $path Path relative to the Vite generated folder.
     *
     * @return string Full file URL.
     * @throws RuntimeException If Vite path is not configured.
     */
    public function getViteFileUrl(string $path): string
    {
        $vitePath = $this->configProvider->getViteGeneratedPath();
        if (!$vitePath) {
            throw new RuntimeException('Vite generated path is not configured.');
        }
        if (!pathinfo($path, PATHINFO_EXTENSION)) {
            $path .= '.js';
        }
        // The framework interpolates the deployed-version segment verbatim, so a
        // stray newline in pub/static/deployed_version.txt leaks into the URL.
        // HTML href/src tolerate the whitespace, but the JSON importmap that
        // consumes these URLs does not — strip it so every Vite URL stays valid.
        return (string)preg_replace('/\s+/', '', $this->getViewFileUrl("{$vitePath}/{$path}"));
    }

    /**
     * Get the full URL for a library file.
     *
     * @param string $path Path relative to the library folder.
     *
     * @return string Full file URL.
     */
    public function getViewLibFileUrl(string $path): string
    {
        return $this->getViteFileUrl(ConfigInterface::LIB_PATH . '/' . $path);
    }

    /**
     * Resolve the file path by its name.
     *
     * @param string $name Format: "Vendor::Path" or "Path".
     * @param string|null $defaultStart Default start path if not specified in $name.
     *
     * @return string Full resolved file URL.
     * @throws InvalidArgumentException If the name is empty.
     */
    public function resolvePathByName(string $name, ?string $defaultStart = null): string
    {
        return $this->getViteFileUrl($this->buildRelativePath($name, $defaultStart));
    }

    /**
     * Build the build-output-relative path for a "Vendor::Path" name.
     *
     * This is the path before it is turned into a URL — i.e. the manifest `file`
     * key for that asset.
     *
     * @param string $name Format: "Vendor::Path" or "Path".
     * @param string|null $defaultStart Default start path if not specified in $name.
     *
     * @return string Path relative to the Vite generated folder, e.g. "Vendor/components/Card".
     * @throws InvalidArgumentException If the name is empty.
     */
    private function buildRelativePath(string $name, ?string $defaultStart = null): string
    {
        if (empty($name)) {
            throw new InvalidArgumentException('The component name cannot be empty.');
        }

        $nameParts = explode('::', $name);
        $vendor = count($nameParts) === 2 ? $nameParts[0] : ConfigInterface::THEME_FILES_PATH;
        $path = count($nameParts) === 2 ? $nameParts[1] : $nameParts[0];

        if ($defaultStart && !str_starts_with($path, "{$defaultStart}/")) {
            $path = "{$defaultStart}/{$path}";
        }

        return "{$vendor}/{$path}";
    }

    /**
     * Resolve the path for a component by its name.
     *
     * @param string $name Component name in the format "Vendor::Component".
     */
    public function resolveComponentPath(string $name): string
    {
        return $this->resolvePathByName($name, ConfigInterface::VUE_COMPONENTS_PATH);
    }

    /**
     * Emit an island marker for a Vue component.
     *
     * Instead of an inline mount script per call, this renders an inert marker
     * that the page-level bootstrap ({@see self::getIslandsRuntimeUrl()})
     * discovers and mounts — by default lazily, when the marker enters the
     * viewport, so below-the-fold components cost nothing until scrolled to.
     * The Vue runtime and i18n plugin load once per page and are shared.
     *
     * @param string $componentName Component name in the format "Vendor::Component".
     * @param array $props Properties to pass to the Vue component.
     * @param bool $eager Mount immediately instead of on viewport entry (above-the-fold).
     *
     * @return string The island marker markup.
     */
    public function renderVueComponent(
        string $componentName,
        array $props = [],
        bool $eager = false,
        string $placeholder = ''
    ): string {
        $relativePath = $this->buildRelativePath($componentName, ConfigInterface::VUE_COMPONENTS_PATH);
        $componentUrl = $this->getViteFileUrl($relativePath);

        // Fails loudly instead of emitting a broken attribute when props are not
        // JSON-encodable.
        $propsAttr = PropsEncoder::encodeAttribute($componentName, $props);
        $componentAttr = htmlspecialchars($componentUrl, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $strategy = $eager ? 'eager' : 'visible';

        // Eager islands mount synchronously at bootstrap. Emit modulepreload for
        // this island's dependency chunks right here, so the browser fetches the
        // whole graph in parallel instead of walking it one round-trip at a time
        // once the bootstrap dynamically imports the component. Emitting per
        // marker (deduplicated across the request) covers islands rendered after
        // the bootstrap block too — e.g. body-end drawers/toasts.
        $preload = $eager ? $this->renderEagerPreload($relativePath . '.js') : '';

        // Server-rendered placeholder sits inside the marker so the slot is not an
        // empty zero-size box before hydration; Vue clears the container on mount
        // (runtime-dom sets innerHTML = '') and swaps in the real component.
        return $preload . <<<HTML
            <div data-mage-island data-component="$componentAttr" data-props="$propsAttr" data-strategy="$strategy">$placeholder</div>
            HTML;
    }

    /**
     * Render the `<link rel="modulepreload">` hints for an eager island's chunk
     * and its transitive static dependencies, skipping any already emitted this
     * request.
     *
     * @param string $componentFile Output-relative chunk path of the island.
     */
    private function renderEagerPreload(string $componentFile): string
    {
        $urls = [];
        foreach ($this->islandManifest->getPreloadFiles([$componentFile]) as $file) {
            $urls[] = $this->getViteFileUrl($file);
        }

        $html = '';
        foreach ($this->eagerIslandRegistry->take($urls) as $url) {
            $href = htmlspecialchars($url, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
            $html .= "<link rel=\"modulepreload\" href=\"{$href}\"/>";
        }

        return $html;
    }

    /**
     * URL of the page-level island bootstrap (loaded once via Block\IslandsRuntime).
     *
     * @return string Full file URL.
     */
    public function getIslandsRuntimeUrl(): string
    {
        return $this->resolvePathByName(self::ISLANDS_RUNTIME_NAME);
    }

    /**
     * Runtime i18n config consumed by the JS translation layer.
     *
     * Exposes the active locale and the URL of Magento's native per-locale
     * `js-translation.json` so the Vue layer can fetch the same dictionary the
     * rest of the storefront uses. Published to the page as
     * `window.__MAGE_OBSIDIAN_I18N__`.
     *
     * @return array{locale: string, dictionaryUrl: string}
     */
    public function getI18nRuntimeConfig(): array
    {
        return [
            'locale' => $this->localeResolver->getLocale(),
            'dictionaryUrl' => $this->getViewFileUrl(self::JS_TRANSLATION_FILE),
        ];
    }

    /**
     * Get the configuration provider.
     *
     * @return ConfigProvider Configuration provider.
     */
    public function getConfigProvider(): ConfigProvider
    {
        return $this->configProvider;
    }

    /**
     * Get the full URL for a Heroicons SVG icon.
     *
     * @param string $iconName Icon name.
     * @param string $iconSet Icon set (solid, outline).
     * @param string $size Icon size (16, 20, 24).
     *
     * @return string Full file URL.
     */
    public function getHeroIcon(
        string $iconName,
        string $iconSet = 'solid',
        string $size = '24',
    ): string {
        if (!pathinfo($iconName, PATHINFO_EXTENSION)) {
            $iconName .= '.svg';
        }
        $url = $this->getViewFileUrl("MageObsidian_ModernFrontend::assets/@heroicons/{$size}/{$iconSet}/{$iconName}");
        return <<<HTML
            <svg width="$size" height="$size" xmlns="http://www.w3.org/2000/svg">
                <use href="$url#icon"></use>
            </svg>
        HTML;
    }
}
