<?php
/**
 * This file is part of the MageObsidian - ModernFrontend project.
 *
 * @license MIT License - See the LICENSE file in the root directory for details.
 * © 2024 Jeanmarcos
 */

namespace MageObsidian\ModernFrontend\Block;

use MageObsidian\ModernFrontend\Api\Data\ConfigInterface;
use MageObsidian\ModernFrontend\Model\Config\ConfigProvider;
use InvalidArgumentException;
use Magento\Framework\View\Element\Template as MagentoTemplate;
use Magento\Framework\View\Element\Template\Context;
use RuntimeException;
use Magento\Framework\Filesystem\Io\File;

/**
 * Class Template
 * Handles integration of modern frontend frameworks with Magento.
 */
class Template extends MagentoTemplate
{
    /**
     * Template constructor.
     *
     * @param Context $context
     * @param ConfigProvider $configProvider
     * @param File $ioFile
     * @param array $data
     */
    public function __construct(
        Context $context,
        private readonly ConfigProvider $configProvider,
        private readonly File $ioFile,
        array $data = []
    ) {
        parent::__construct($context, $data);
    }

    /**
     * Get the full URL for a file generated by Vite.
     *
     * @param string $path Path relative to the Vite generated folder.
     *
     * @return string Full file URL.
     * @throws RuntimeException If Vite path is not configured.
     */
    public function getViteFileUrl(string $path): string
    {
        $vitePath = $this->configProvider->getViteGeneratedPath();
        if (!$vitePath) {
            throw new RuntimeException('Vite generated path is not configured.');
        }
        if (!pathinfo($path, PATHINFO_EXTENSION)) {
            $path .= '.js';
        }
        return $this->getViewFileUrl("{$vitePath}/{$path}");
    }

    /**
     * Get the full URL for a library file.
     *
     * @param string $path Path relative to the library folder.
     *
     * @return string Full file URL.
     */
    public function getViewLibFileUrl(string $path): string
    {
        return $this->getViteFileUrl(ConfigInterface::LIB_PATH . '/' . $path);
    }

    /**
     * Resolve the file path by its name.
     *
     * @param string $name Format: "Vendor::Path" or "Path".
     * @param string|null $defaultStart Default start path if not specified in $name.
     *
     * @return string Full resolved file URL.
     * @throws InvalidArgumentException If the name is empty.
     */
    public function resolvePathByName(string $name, ?string $defaultStart = null): string
    {
        if (empty($name)) {
            throw new InvalidArgumentException('The component name cannot be empty.');
        }

        $nameParts = explode('::', $name);
        $vendor = count($nameParts) === 2 ? $nameParts[0] : ConfigInterface::THEME_FILES_PATH;
        $path = count($nameParts) === 2 ? $nameParts[1] : $nameParts[0];

        if ($defaultStart && !str_starts_with($path, "{$defaultStart}/")) {
            $path = "{$defaultStart}/{$path}";
        }

        return $this->getViteFileUrl("{$vendor}/{$path}");
    }

    /**
     * Generates the HTML to load a Vue component dynamically.
     *
     * @param string $componentName Component name in the format "Vendor::Component".
     * @param array $props Properties to pass to the Vue component.
     *
     * @return string HTML code to integrate the Vue component.
     */
    public function renderVueComponent(string $componentName, array $props = []): string
    {
        $componentPath = $this->resolvePathByName($componentName, ConfigInterface::VUE_COMPONENTS_PATH);
        $vueUrl = $this->getViewLibFileUrl('vue');

        // Generate a unique ID for the Vue component's container.
        $uniqueId = 'vue-component-' . uniqid();

        // Convert properties to JSON format for JavaScript.
        $propsJson = json_encode($props, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP);

        // Return the HTML and JavaScript needed to mount the Vue component.
        return <<<HTML
            <div id="$uniqueId"></div>
            <script type="module">
                import { createApp } from '$vueUrl';
                import Component from '$componentPath';
                try {
                    createApp(Component, $propsJson).mount('#$uniqueId');
                } catch (error) {
                    console.error('Failed to mount Vue component:', error);
                }
            </script>
        HTML;
    }

    /**
     * Get the configuration provider.
     *
     * @return ConfigProvider Configuration provider.
     */
    public function getConfigProvider(): ConfigProvider
    {
        return $this->configProvider;
    }

    public function getChildHtmlWithExclusions($alias = '', $useCache = true, $excludedBlocks = [])
    {
        $layout = $this->getLayout();
        if (!$layout) {
            return '';
        }
        $name = $this->getNameInLayout();
        $out = '';
        if ($alias) {
            $childName = $layout->getChildName($name, $alias);
            if ($childName && !in_array($childName, $excludedBlocks, true)) {
                $out = $layout->renderElement($childName, $useCache);
            }
        } else {
            foreach ($layout->getChildNames($name) as $child) {
                if (!in_array($child, $excludedBlocks, true)) {
                    $out .= $layout->renderElement($child, $useCache);
                }
            }
        }

        return $out;
    }

    /**
     * Get the full URL for a Heroicons SVG icon.
     *
     * @param string $iconName Icon name.
     * @param string $iconSet Icon set (solid, outline).
     * @param string $size Icon size (16, 20, 24).
     *
     * @return string Full file URL.
     */
    public function getHeroIcon(
        string $iconName,
        string $iconSet = 'solid',
        string $size = '24',
    ): string {
        if (!pathinfo($iconName, PATHINFO_EXTENSION)) {
            $iconName .= '.svg';
        }
        $url = $this->getViewFileUrl("MageObsidian_ModernFrontend::assets/@heroicons/{$size}/{$iconSet}/{$iconName}");
        return <<<HTML
            <svg width="$size" height="$size" mlns="http://www.w3.org/2000/svg">
                <use href="$url#icon"></use>
            </svg>
        HTML;
    }
}
